### ISSUE TITLE
Убрать overflow

### ISSUE THREAD

**Issue by vladimirperepelytsia** [yamixa-gz/entry-task#1]
https://github.com/yamixa-gz/entry-task/blob/f4efa8d24f6aa8c008931ef948d7ace8eb237cce/src/scss/App.scss#L6
верстка не должна вылазить за пределы блока даже при отсутствии этого свойства

**Comment by mykhailo-zanizdra-dev** [comment]
fixed
https://github.com/yamixa-gz/entry-task/blob/1209b71879450b5f70d0d6b7fef550d2029328b9/src/scss/App.scss#L6
