### ISSUE TITLE
Проверка на сущестрование в обьекте в withTranslation

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [yamixa-gz/entry-task#10]
Вместе кучи действий `!Object.keys(languages).includes(APP_LANGUAGE)` можно заменить на `!languages[APP_LANGUAGE]`

Тоже самое с `Object.entries(languages).find((entry) => entry[0] === APP_LANGUAGE)[1]`
Если я все правильно понял то можно заменить на `languages[APP_LANGUAGE]`

**Comment by mykhailo-zanizdra-dev** [comment]
Да ты прав, ну да так просто, странно что я сразу не понял) ну, бывает...))
