### ISSUE TITLE
Строки вроде 'ascending' лучше вынести в отдельно

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [yamixa-gz/entry-task#5]
Такие строки лучше сохранить в const над компонентой чтобы при написании не было опечаток. В случае если такие строки используются в нескольких файлах, то лучше создать файл с константами и доставать их уже оттуда

**Comment by mykhailo-zanizdra-dev** [comment]
done! Возможно перестарался. Подсказывай, если что)
